services:

  carla-server:
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    privileged: True
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    image: $SIMULATOR_IMAGE
    command: bash -ic './CarlaUE4.sh -nosound $SIMULATOR_FLAGS 2>/dev/null'

  carla-scenario-runner:
    depends_on:
      carla-server:
        condition: service_healthy
    volumes:
      - $SCENARIO_FOLDER_PATH:/scenarios
    image: $SCENARIO_RUNNER_IMAGE
    command: bash -ic "python ./scenario_runner.py --host carla-server --openscenario /scenarios/$SCENARIO_FILE_NAME --output"