general_settings:
    max_simulation_time: 60
    max_real_time: 300
    simulation_services:
        - carla-server
        - time-health-check
        - spawned-vehicle-check
        - carla-ros-bridge
        - carla-scenario-runner
        - rosbag-record
    convert_services: []
    record_topics:
        topic_rgb: /carla/ego_vehicle/rgb/image
        topic_segmentation: /carla/ego_vehicle/segmentation/image
        topic_tf: /tf
        topic_clock: /clock
    output_path: ./data/scenario-execution/

run_settings:
    num_executions: 1
    scenario_settings:
        scenario_file:
            - ../utils/scenarios/town01.xosc
            - ../utils/scenarios/town10.xosc
        sensors_file:
            - ./config/sensors/rgb_segmentation_camera.json
